server:
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      mayosen:
        academy: DEBUG

spring:
  jpa:
    open-in-view: true
    properties:
      hibernate:
        generate_statistics: true
