server:
  port: ${PORT}

logging:
  level:
    org:
      springframework:
        web: WARN
    com:
      mayosen:
        academy: WARN

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        order_inserts: true
        jdbc:
          batch_size: 30


  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
