ALTER TABLE IF EXISTS update_history DROP CONSTRAINT IF EXISTS item_id_fk;
DROP INDEX IF EXISTS update_date_index;
DROP TABLE IF EXISTS update_history;

CREATE TABLE update_history(
    update_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_id VARCHAR(255) NOT NULL,
    url VARCHAR(255),
    date timestamptz NOT NULL,
    parent_id VARCHAR(255),
    type VARCHAR(10) NOT NULL,
    size bigint
);

ALTER TABLE update_history ADD CONSTRAINT item_id_fk
    FOREIGN KEY (item_id) REFERENCES system_item(item_id) ON DELETE CASCADE;

CREATE INDEX update_date_index ON update_history(date);
